# ===================================
# BASIC SETTINGS
# ===================================
baseURL = 'https://rizkynotes.com/'
languageCode = 'id-ID'
title = "Rizky Note's"
theme = ''

# ===================================
# BUILD SETTINGS
# ===================================
[build]
  writeStats = true

# ===================================
# MARKUP SETTINGS
# ===================================
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'monokai' # ref: https://xyproto.github.io/splash/docs/
    lineNos = true

# ===================================
# PARAMS (Custom Parameters)
# ===================================
[params]
  description = 'Website blog pribadi membahas tentang backend engineer'
  author = 'Rizky Darmawan'

   # Default OG Image (for homepage & pages without image)
  image = '/images/og-image.png'

  # Social Media
  [params.social]
    instagram = 'https://www.instagram.com/rizky.notes/'
    github = 'https://github.com/letenk"'
    linkedin = 'https://www.linkedin.com/in/rizkydarmawan/"'

# ===================================
# MENU NAVIGATION
# ===================================
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 2

  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3

# ===================================
# OUTPUTS
# ===================================
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']

# ===================================
# SITEMAP CONFIGURATION
# ===================================
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# ===================================
# TAXONOMIES
# ===================================
[taxonomies]
  tag = 'tags'
  category = 'categories'

# ===================================
# PRIVACY & SECURITY
# ===================================
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

# ===================================
# PERMALINKS
# ===================================
[permalinks]
  posts = '/posts/:slug/'
